version: '3.5'

services:
  db_auth:
    container_name: db_auth
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=Qwerty3366
      - POSTGRES_USER=admindb
    image: postgres:14.8-alpine
