server:
  port : 8085

cbr:
  baseUrl : "https://cbr.ru/scripts/XML_daily.asp"


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    enabled: false

spring:
  application:
    name: currency-rate-service